import type { LookupResponse, TrialMatch } from './backend'

const RPE65_TRIAL_WARNINGS = [
  'clinical_trials_discovery_only:not_eligibility',
  'clinical_trials_gene_level_match:not_variant_specific',
]

const RPE65_TRIAL_ROWS: TrialMatch[] = [
  {
    nct_id: 'NCT06088992',
    title: 'Leber Congenital Amaurosis Inherited Blindness of Gene Therapy Trial (LIGHT)',
    status: 'ACTIVE_NOT_RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT06088992',
    warnings: RPE65_TRIAL_WARNINGS,
  },
  {
    nct_id: 'NCT06196827',
    title: 'Safety and Tolerability of LX101 for Inherited Retinal Dystrophy Associated With RPE65',
    status: 'ACTIVE_NOT_RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT06196827',
    warnings: RPE65_TRIAL_WARNINGS,
  },
  {
    nct_id: 'NCT04516369',
    title: 'Study of Efficacy and Safety of Voretigene Neparvovec in Japanese Patients',
    status: 'ACTIVE_NOT_RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT04516369',
    warnings: RPE65_TRIAL_WARNINGS,
  },
  {
    nct_id: 'NCT07265895',
    title: 'Inherited Retinal Diseases: Natural History and Genotype-Phenotype Correlations',
    status: 'NOT_YET_RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT07265895',
    warnings: RPE65_TRIAL_WARNINGS,
  },
  {
    nct_id: 'NCT00481546',
    title: 'Phase I Trial of Gene Vector to Patients With Retinal Disease Due to RPE65 Mutations',
    status: 'ACTIVE_NOT_RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT00481546',
    warnings: RPE65_TRIAL_WARNINGS,
  },
  {
    nct_id: 'NCT00999609',
    title: 'Safety and Efficacy Study in Subjects With Leber Congenital Amaurosis',
    status: 'ACTIVE_NOT_RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT00999609',
    warnings: RPE65_TRIAL_WARNINGS,
  },
  {
    nct_id: 'NCT07054632',
    title: 'Efficacy and Safety of LX101 for Inherited Retinal Dystrophy',
    status: 'ACTIVE_NOT_RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT07054632',
    warnings: RPE65_TRIAL_WARNINGS,
  },
  {
    nct_id: 'NCT03602820',
    title: 'Long-term Follow-up Study in Subjects Who Received Voretigene Neparvovec-rzyl',
    status: 'ACTIVE_NOT_RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT03602820',
    warnings: RPE65_TRIAL_WARNINGS,
  },
  {
    nct_id: 'NCT06212297',
    title: 'Fellow-eye Study of LX101 in Subjects With Inherited Retinal Dystrophy',
    status: 'ACTIVE_NOT_RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT06212297',
    warnings: RPE65_TRIAL_WARNINGS,
  },
  {
    nct_id: 'NCT05858983',
    title: 'Gene Therapy in Subjects With Biallelic RPE65 Mutation-associated Retinal Dystrophy',
    status: 'RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT05858983',
    warnings: RPE65_TRIAL_WARNINGS,
  },
  {
    nct_id: 'NCT06024057',
    title: 'Expanded Clinical Study Evaluating AAV2-RPE65 Gene Therapy',
    status: 'NOT_YET_RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT06024057',
    warnings: RPE65_TRIAL_WARNINGS,
  },
  {
    nct_id: 'NCT05906953',
    title: 'Safety and Efficacy Trial of HG004 for Leber Congenital Amaurosis',
    status: 'RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT05906953',
    warnings: RPE65_TRIAL_WARNINGS,
  },
  {
    nct_id: 'NCT01208389',
    title: 'Phase 1 Follow-on Study of AAV2-hRPE65v2 Vector',
    status: 'ACTIVE_NOT_RECRUITING',
    phase: null,
    conditions: [],
    interventions: [],
    locations: [],
    match_level: 'gene_level',
    matched_terms: ['RPE65'],
    source_url: 'https://clinicaltrials.gov/study/NCT01208389',
    warnings: RPE65_TRIAL_WARNINGS,
  },
]

export const RPE65_SAMPLE: LookupResponse = {
  query: 'RPE65 c.260A>G',
  species: 'human',
  warnings: [],
  report_payload: {
    patient_id: 'sample',
    case_label: 'RPE65 p.Asp87Gly',
    report_title: 'RPE65 c.260A>G — Variant Interpretation Report',
    clinical_phenotype: 'Leber Congenital Amaurosis 2 (LCA2) / Retinitis Pigmentosa 20 (RP20). Autosomal recessive retinal dystrophy characterised by severe visual impairment from infancy, nystagmus, and markedly reduced or absent ERG response.',
    ai_clinical_summary:
      'RPE65 p.Asp87Gly is concordant with autosomal recessive retinal dystrophy phenotypes. ClinVar lists it as Likely Pathogenic with two-star review status, supported by REVEL 0.82 - above the strong pathogenic threshold. ClinicalTrials.gov currently returns 13 active/not-yet RPE65 records in the report search, including recruiting gene-therapy studies and long-term follow-up studies. Voretigene neparvovec (Luxturna) is FDA-approved for confirmed biallelic RPE65 retinal dystrophy. Confirmation of biallelic status and segregation testing are the immediate next steps before clinical decision-making proceeds.',
    variant_summary_rows: [
      {
        gene: 'RPE65',
        transcript_hgvs: 'NM_000329.3:c.260A>G',
        protein_change: 'p.Asp87Gly',
        genomic_hg38: 'chr1:68,894,934A>G',
        variation_type: 'SNV',
        consequence: 'missense_variant',
      },
    ],
    acmg_classification: 'Likely Pathogenic — ACMG/AMP criteria: PM1, PM2, PP3 (REVEL 0.82). ClinVar VCV000099473 · 2 stars · 4 submitters.',
    expanded_evidence:
      'ClinVar: Likely Pathogenic (2 stars, 4 submitters, VCV000099473). gnomAD v4 joint: AC 2 / AN 125,748 / AF 0.0000159, with popmax NFE AF 0.0000486 and no homozygotes reported. VEP: missense, moderate impact, SIFT deleterious (0.01), PolyPhen-2 probably damaging (0.987). SpliceAI: max delta score 0.04 (below splicing threshold). REVEL: 0.82 - high support for pathogenicity.',
    clinical_integration:
      'Variant is consistent with RPE65-associated Leber Congenital Amaurosis 2 (LCA2) and Retinitis Pigmentosa 20. Biallelic pathogenic variants in RPE65 cause the autosomal recessive form. Luxturna (voretigene neparvovec) is FDA-approved gene therapy for confirmed biallelic RPE65 mutations.',
    expected_symptoms:
      'Severe visual impairment from infancy or early childhood, nystagmus, photophobia, absent or markedly reduced ERG, preserved retinal structure in early years with progressive degeneration.',
    recommendations:
      'Confirm biallelic status: segregation analysis and phasing of any second RPE65 variant. Ophthalmology review with ERG and retinal imaging. Genetic counselling for family members. Evaluate eligibility for Luxturna gene therapy if biallelic RPE65 pathogenic variants confirmed.',
    therapeutic_landscape:
      'Voretigene neparvovec (Luxturna, Spark Therapeutics) is FDA-approved (2017) for confirmed biallelic RPE65 mutation-associated retinal dystrophy.\n\nClinicalTrials.gov RPE65 search currently returns 13 active/not-yet records in the report filter and 29 total RPE65 search records. The structured list below is discovery-only: it is gene-level, not variant-specific eligibility guidance.',
    limitations: null,
    variant_decoder:
      'c.260A>G — position 260 in the coding sequence of NM_000329.3; adenine substituted by guanine. This changes codon 87 from GAC (Aspartate/Asp/D) to GGC (Glycine/Gly/G). Asp87 is located in the retinoid isomerohydrolase catalytic domain; Gly substitution removes a charged side chain critical for substrate binding.',
    pubmed_articles: [
      {
        pmid: '28274730',
        title: 'Pharmacological and gene therapy based rescue of cytochrome P450-mediated monooxygenase deficiency in RPE65',
        authors: 'Cheng T, Bhatt A, Kulkarni A et al.',
        journal: 'Invest Ophthalmol Vis Sci',
        year: '2017',
        url: 'https://pubmed.ncbi.nlm.nih.gov/28274730/',
      },
    ],
    ai_generated_sections: ['ai_clinical_summary', 'clinical_integration', 'recommendations', 'variant_decoder'],
    locus_context: {
      gene: 'RPE65',
      centre_cdna: 'c.260A>G',
      coords: 'chr1 : 68,444,849 — 68,444,889  ·  RPE65 exon 4  ·  (+) strand',
      nearby_variants: [
        { cds_pos: -42, classification: 'pathogenic',        hgvs: 'c.236A>G', clinvar_id: null,      protein_change: 'p.Asp79Gly' },
        { cds_pos: -32, classification: 'likely_pathogenic', hgvs: 'c.241C>T', clinvar_id: null,      protein_change: 'p.Arg81Cys' },
        { cds_pos: -24, classification: 'pathogenic',        hgvs: 'c.247G>A', clinvar_id: null,      protein_change: 'p.Ala83Thr' },
        { cds_pos: -16, classification: 'vus',               hgvs: 'c.253T>C', clinvar_id: null,      protein_change: null },
        { cds_pos: -8,  classification: 'likely_pathogenic', hgvs: 'c.257C>G', clinvar_id: null,      protein_change: null },
        { cds_pos: 0,   classification: 'likely_pathogenic', hgvs: 'c.260A>G', clinvar_id: '1421454', protein_change: 'p.Asp87Gly' },
        { cds_pos: 8,   classification: 'vus',               hgvs: 'c.268A>G', clinvar_id: null,      protein_change: null },
        { cds_pos: 16,  classification: 'likely_benign',     hgvs: 'c.271G>A', clinvar_id: null,      protein_change: null },
        { cds_pos: 24,  classification: 'pathogenic',        hgvs: 'c.277C>T', clinvar_id: null,      protein_change: 'p.Arg93Cys' },
        { cds_pos: 32,  classification: 'vus',               hgvs: 'c.283G>C', clinvar_id: null,      protein_change: null },
        { cds_pos: 40,  classification: 'likely_pathogenic', hgvs: 'c.289G>A', clinvar_id: null,      protein_change: 'p.Glu97Lys' },
      ],
      codon_strip: [
        { codon_number: 82, aa_ref: 'Y', aa_alt: null, dna_ref: 'TAT', dna_alt: null,  is_query: false },
        { codon_number: 83, aa_ref: 'R', aa_alt: null, dna_ref: 'CGG', dna_alt: null,  is_query: false },
        { codon_number: 84, aa_ref: 'E', aa_alt: null, dna_ref: 'GAA', dna_alt: null,  is_query: false },
        { codon_number: 85, aa_ref: 'P', aa_alt: null, dna_ref: 'CCT', dna_alt: null,  is_query: false },
        { codon_number: 86, aa_ref: 'V', aa_alt: null, dna_ref: 'GTG', dna_alt: null,  is_query: false },
        { codon_number: 87, aa_ref: 'D', aa_alt: 'G',  dna_ref: 'GAC', dna_alt: 'GGC', is_query: true },
        { codon_number: 88, aa_ref: 'K', aa_alt: null, dna_ref: 'AAG', dna_alt: null,  is_query: false },
        { codon_number: 89, aa_ref: 'T', aa_alt: null, dna_ref: 'ACA', dna_alt: null,  is_query: false },
        { codon_number: 90, aa_ref: 'V', aa_alt: null, dna_ref: 'GTC', dna_alt: null,  is_query: false },
        { codon_number: 91, aa_ref: 'A', aa_alt: null, dna_ref: 'GCC', dna_alt: null,  is_query: false },
        { codon_number: 92, aa_ref: 'I', aa_alt: null, dna_ref: 'ATT', dna_alt: null,  is_query: false },
      ],
    },
    in_silico_predictions: {
      cards: [
        { name: 'REVEL',         score: 0.82, threshold: 0.75, verdict: 'damaging',  verdict_label: 'Pathogenic supporting', source_url: 'https://sites.google.com/site/revelgenomics' },
        { name: 'AlphaMissense', score: 0.91, threshold: 0.56, verdict: 'damaging',  verdict_label: 'Likely pathogenic',     source_url: 'https://alphamissense.hegelab.org' },
        { name: 'MetaLR',        score: 0.78, threshold: 0.50, verdict: 'damaging',  verdict_label: 'Deleterious',           source_url: null },
        { name: 'SpliceAI',      score: 0.05, threshold: 0.20, verdict: 'tolerated', verdict_label: 'No splice impact',      source_url: 'https://spliceailookup.broadinstitute.org' },
      ],
      consensus_note:
        'Predictors converge: the protein-effect predictors all cross their pathogenic thresholds, while SpliceAI sits well below the 0.20 splice-altering cutoff. No disagreement to flag — the in-silico signal is internally consistent with the ClinVar Likely Pathogenic call.',
    },
    acmg_criteria_scaffold: {
      criteria: [
        { code: 'PVS1', verdict: 'not_met' },
        { code: 'PS1',  verdict: 'not_met' },
        { code: 'PS2',  verdict: 'not_assessed' },
        { code: 'PS3',  verdict: 'not_assessed' },
        { code: 'PS4',  verdict: 'not_assessed' },
        { code: 'PM1',  verdict: 'not_met' },
        { code: 'PM2',  verdict: 'met', note: 'Rare in gnomAD v4 joint with AC 2 / AN 125,748; no homozygotes reported.' },
        { code: 'PM3',  verdict: 'not_assessed' },
        { code: 'PM4',  verdict: 'not_met' },
        { code: 'PM5',  verdict: 'met', note: 'Different missense at same codon previously classified pathogenic.' },
        { code: 'PM6',  verdict: 'not_assessed' },
        { code: 'PP1',  verdict: 'not_assessed' },
        { code: 'PP2',  verdict: 'not_met' },
        { code: 'PP3',  verdict: 'met', note: 'Multiple in-silico predictors agree on damaging.' },
        { code: 'PP4',  verdict: 'met', note: 'Phenotype highly specific for RPE65-related disease.' },
        { code: 'PP5',  verdict: 'not_assessed' },
        { code: 'BA1',  verdict: 'not_met' },
        { code: 'BS1',  verdict: 'not_met' },
        { code: 'BS2',  verdict: 'not_assessed' },
        { code: 'BS3',  verdict: 'not_assessed' },
        { code: 'BS4',  verdict: 'not_assessed' },
        { code: 'BP1',  verdict: 'not_met' },
        { code: 'BP2',  verdict: 'not_assessed' },
        { code: 'BP3',  verdict: 'not_met' },
        { code: 'BP4',  verdict: 'not_met' },
        { code: 'BP5',  verdict: 'not_assessed' },
        { code: 'BP6',  verdict: 'not_assessed' },
        { code: 'BP7',  verdict: 'not_met' },
      ],
      intro:
        'An automated read of the standard ACMG/AMP criteria for this variant. This is supporting evidence, not a classification. Eamos does not issue ACMG classifications — clinical judgement, segregation, and functional data are required before a final call.',
      note:
        'Met criteria above provide moderate-to-supporting evidence consistent with the Likely Pathogenic ClinVar classification. The unmet criteria reflect evidence types that haven’t been observed for this variant (e.g. functional studies, de novo observation) — they do not contradict pathogenicity.',
      disclaimer: 'Supporting evidence, not classification.',
    },
    curated_variants_distribution: {
      cells: {
        pathogenic_lof: 210,
        pathogenic_missense: 187,
        pathogenic_noncoding: 6,
        pathogenic_synonymous: 3,
        vus_lof: 1,
        vus_missense: 342,
        vus_noncoding: 51,
        vus_synonymous: 32,
        benign_lof: 0,
        benign_missense: 11,
        benign_noncoding: 198,
        benign_synonymous: 245,
      },
      row_totals: { pathogenic: 406, vus: 426, benign: 454 },
      total: 1286,
      subtitle: '1,286 classified variants · ClinVar + UniProt',
      reading:
        'LOF and missense both contribute substantially to pathogenicity in RPE65 — LOF is a well-established disease mechanism. The 342 missense VUS reflect the deep interpretation tail typical of recessive disease genes.',
    },
    associated_conditions: [
      { name: 'Leber Congenital Amaurosis 2 (LCA2)',                 case_count: 412, evidence_level: 'definitive', inheritance: 'AR', source: 'OMIM #204100',            db_tag: '#204100',               db_tag_bold: 'OMIM', source_list: 'OMIM · Monarch · DECIPHER · GenCC · ClinGen' },
      { name: 'Retinitis Pigmentosa 20 (RP20)',                      case_count: 218, evidence_level: 'definitive', inheritance: 'AR', source: 'OMIM #613794',            db_tag: '#613794',               db_tag_bold: 'OMIM', source_list: 'OMIM · Monarch · GenCC' },
      { name: 'RPE65-Related Dominant Retinopathy',                  case_count: 14,  evidence_level: 'moderate',   inheritance: 'AD', source: 'No OMIM entry',           db_tag: 'No OMIM entry',         db_tag_bold: null,   source_list: 'OMIM · GenCC · ClinGen · MONDO' },
      { name: 'Severe Early-Childhood-Onset Retinal Dystrophy',      case_count: 9,   evidence_level: 'moderate',   inheritance: 'AR', source: 'Orphanet ORPHA:71862',    db_tag: 'Orphanet ORPHA:71862',  db_tag_bold: null,   source_list: 'Orphanet · GenCC' },
      { name: 'RPE65-Related Recessive Retinopathy (umbrella)',      case_count: 5,   evidence_level: 'definitive', inheritance: 'AR', source: 'MONDO:0019200',           db_tag: 'MONDO:0019200',         db_tag_bold: null,   source_list: 'PubMed · GenCC · MONDO · DECIPHER · OMIM · ClinGen' },
    ],
    publications_callout: {
      total_count: 816,
      scholar_url: 'https://scholar.google.com/scholar?q=RPE65+Asp87Gly',
      blurb: 'Across PubMed and Google Scholar for RPE65 + p.Asp87Gly. Ask Eamos for a synthesis of the top 5, or browse externally.',
      ai_summary_prompt: 'Summarise the key publications on RPE65 c.260A>G in plain language for a clinician.',
    },
    population_frequency_detail: {
      source: 'gnomAD',
      dataset: 'gnomad_r4',
      variant_id: '1-68444869-T-C',
      sequencing_type: 'joint',
      allele_frequency: 0.0000159,
      allele_count: 2,
      allele_number: 125748,
      homozygote_count: 0,
      popmax_frequency: 0.0000486,
      popmax_population: 'nfe',
      genetic_ancestry_groups: [
        { id: 'nfe', allele_count: 2, allele_number: 41152, allele_frequency: 0.0000486, homozygote_count: 0 },
        { id: 'afr', allele_count: 0, allele_number: 31240, allele_frequency: 0, homozygote_count: 0 },
        { id: 'eas', allele_count: 0, allele_number: 19906, allele_frequency: 0, homozygote_count: 0 },
        { id: 'amr', allele_count: 0, allele_number: 18330, allele_frequency: 0, homozygote_count: 0 },
        { id: 'sas', allele_count: 0, allele_number: 15210, allele_frequency: 0, homozygote_count: 0 },
        { id: 'fin', allele_count: 0, allele_number: 10428, allele_frequency: 0, homozygote_count: 0 },
        { id: 'asj', allele_count: 0, allele_number: 10020, allele_frequency: 0, homozygote_count: 0 },
        { id: 'mid', allele_count: 0, allele_number: 4200, allele_frequency: 0, homozygote_count: 0 },
      ],
      age_distribution: {
        het: {
          bin_edges: [30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80],
          bin_freq: [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
          n_smaller: 0,
          n_larger: 0,
        },
        hom: {
          bin_edges: [30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80],
          bin_freq: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          n_smaller: 0,
          n_larger: 0,
        },
      },
      flags: [],
      warnings: [],
      source_url: 'https://gnomad.broadinstitute.org/variant/1-68444869-T-C?dataset=gnomad_r4',
    },
    report_profile: {
      population_frequency: {
        section_number: 3,
        section_id: 'section-3-population-frequency',
        panel_id: 'gnomad-expansion',
        title: 'gnomAD Population Frequency Detail',
        detail_ref: 'population_frequency_detail',
        source_status: 'fixture',
        dataset: 'gnomad_r4',
        genome_build: 'GRCh38',
        variant_id: '1-68444869-T-C',
        sequencing_type: 'joint',
        visual_scale: {
          basis: 'popmax_frequency',
          min_value: 0,
          max_value: 0.0000486,
          max_group_id: 'nfe',
          warnings: [],
        },
        visual_groups: [
          { id: 'nfe', label: 'Non-Finnish European genetic ancestry', allele_frequency: 0.0000486, allele_count: 2, allele_number: 41152, homozygote_count: 0, is_popmax: true, data_state: 'observed', sort_order: 1, warnings: [] },
          { id: 'afr', label: 'African/African American genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 31240, homozygote_count: 0, is_popmax: false, data_state: 'zero_observed', sort_order: 2, warnings: [] },
          { id: 'eas', label: 'East Asian genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 19906, homozygote_count: 0, is_popmax: false, data_state: 'zero_observed', sort_order: 3, warnings: [] },
          { id: 'amr', label: 'Admixed American genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 18330, homozygote_count: 0, is_popmax: false, data_state: 'zero_observed', sort_order: 4, warnings: [] },
          { id: 'sas', label: 'South Asian genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 15210, homozygote_count: 0, is_popmax: false, data_state: 'zero_observed', sort_order: 5, warnings: [] },
          { id: 'fin', label: 'Finnish genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 10428, homozygote_count: 0, is_popmax: false, data_state: 'zero_observed', sort_order: 6, warnings: [] },
          { id: 'asj', label: 'Ashkenazi Jewish genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 10020, homozygote_count: 0, is_popmax: false, data_state: 'zero_observed', sort_order: 7, warnings: [] },
          { id: 'mid', label: 'Middle Eastern genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 4200, homozygote_count: 0, is_popmax: false, data_state: 'zero_observed', sort_order: 8, warnings: [] },
        ],
        age_histograms: [
          {
            genotype: 'heterozygous_alternate',
            scope: 'overall_release_samples',
            group_id: null,
            bins: [
              { label: '30-35', lower_bound: 30, upper_bound: 35, count: 0 },
              { label: '35-40', lower_bound: 35, upper_bound: 40, count: 0 },
              { label: '40-45', lower_bound: 40, upper_bound: 45, count: 0 },
              { label: '45-50', lower_bound: 45, upper_bound: 50, count: 1 },
              { label: '50-55', lower_bound: 50, upper_bound: 55, count: 0 },
              { label: '55-60', lower_bound: 55, upper_bound: 60, count: 1 },
              { label: '60-65', lower_bound: 60, upper_bound: 65, count: 0 },
              { label: '65-70', lower_bound: 65, upper_bound: 70, count: 0 },
              { label: '70-75', lower_bound: 70, upper_bound: 75, count: 0 },
              { label: '75-80', lower_bound: 75, upper_bound: 80, count: 0 },
            ],
            n_smaller: 0,
            n_larger: 0,
            warnings: ['age_distribution_scope:overall_release_samples'],
          },
          {
            genotype: 'homozygous_alternate',
            scope: 'overall_release_samples',
            group_id: null,
            bins: [
              { label: '30-35', lower_bound: 30, upper_bound: 35, count: 0 },
              { label: '35-40', lower_bound: 35, upper_bound: 40, count: 0 },
              { label: '40-45', lower_bound: 40, upper_bound: 45, count: 0 },
              { label: '45-50', lower_bound: 45, upper_bound: 50, count: 0 },
              { label: '50-55', lower_bound: 50, upper_bound: 55, count: 0 },
              { label: '55-60', lower_bound: 55, upper_bound: 60, count: 0 },
              { label: '60-65', lower_bound: 60, upper_bound: 65, count: 0 },
              { label: '65-70', lower_bound: 65, upper_bound: 70, count: 0 },
              { label: '70-75', lower_bound: 70, upper_bound: 75, count: 0 },
              { label: '75-80', lower_bound: 75, upper_bound: 80, count: 0 },
            ],
            n_smaller: 0,
            n_larger: 0,
            warnings: ['age_distribution_scope:overall_release_samples'],
          },
        ],
        source_rows: [
          { group_id: 'nfe', label: 'Non-Finnish European genetic ancestry', allele_frequency: 0.0000486, allele_count: 2, allele_number: 41152, homozygote_count: 0, is_popmax: true, warnings: [] },
          { group_id: 'afr', label: 'African/African American genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 31240, homozygote_count: 0, is_popmax: false, warnings: [] },
          { group_id: 'eas', label: 'East Asian genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 19906, homozygote_count: 0, is_popmax: false, warnings: [] },
          { group_id: 'amr', label: 'Admixed American genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 18330, homozygote_count: 0, is_popmax: false, warnings: [] },
          { group_id: 'sas', label: 'South Asian genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 15210, homozygote_count: 0, is_popmax: false, warnings: [] },
          { group_id: 'fin', label: 'Finnish genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 10428, homozygote_count: 0, is_popmax: false, warnings: [] },
          { group_id: 'asj', label: 'Ashkenazi Jewish genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 10020, homozygote_count: 0, is_popmax: false, warnings: [] },
          { group_id: 'mid', label: 'Middle Eastern genetic ancestry', allele_frequency: 0, allele_count: 0, allele_number: 4200, homozygote_count: 0, is_popmax: false, warnings: [] },
        ],
        source_url: 'https://gnomad.broadinstitute.org/variant/1-68444869-T-C?dataset=gnomad_r4',
        warnings: [
          'age_distribution_scope:overall_release_samples',
          'per_genetic_ancestry_age_distribution_not_available',
        ],
        provenance: [
          {
            source: 'gnomAD',
            status: 'fixture',
            query: { variant_id: '1-68444869-T-C', dataset: 'gnomad_r4' },
            source_url: 'https://gnomad.broadinstitute.org/variant/1-68444869-T-C?dataset=gnomad_r4',
            retrieved_at: null,
            version: 'r4',
            warnings: [],
          },
        ],
      },
      therapies_trials: {
        trial_rows: RPE65_TRIAL_ROWS,
        warnings: [
          'clinical_trials_discovery_only:not_eligibility',
          'clinical_trials_gene_level_target_only',
          'clinical_trials_gene_level_match:not_variant_specific',
        ],
        provenance: [
          {
            source: 'ClinicalTrials.gov',
            status: 'live',
            query: { query: 'RPE65' },
            source_url: 'https://clinicaltrials.gov/search?cond=rpe65&viewType=Card',
            retrieved_at: null,
            version: null,
            warnings: [
              'clinical_trials_discovery_only:not_eligibility',
              'clinical_trials_gene_level_match:not_variant_specific',
            ],
          },
        ],
      },
      provenance: [],
    },
  },
  evidence: [
    {
      source: 'clinvar',
      status: 'completed',
      request_identity: { gene: 'RPE65', cdna: 'c.260A>G' },
      summary: {
        classification: 'Likely pathogenic',
        review_stars: 2,
        submitter_count: 4,
        accession: 'VCV000099473',
        condition: 'Leber congenital amaurosis 2',
      },
      warnings: [],
      source_url: 'https://www.ncbi.nlm.nih.gov/clinvar/variation/99473/',
    },
    {
      source: 'vep',
      status: 'completed',
      request_identity: { transcript: 'NM_000329.3', cdna: 'c.260A>G' },
      summary: {
        consequence: 'missense_variant',
        impact: 'MODERATE',
        sift: { pred: 'deleterious', score: 0.01 },
        polyphen: { pred: 'probably_damaging', score: 0.987 },
        revel: 0.82,
      },
      warnings: [],
      source_url: 'https://www.ensembl.org/Tools/VEP',
    },
    {
      source: 'spliceai',
      status: 'completed',
      request_identity: { gene: 'RPE65', cdna: 'c.260A>G' },
      summary: {
        max_delta: 0.04,
        interpretation: 'Low splicing impact',
      },
      warnings: [],
      source_url: 'https://spliceailookup.broadinstitute.org/',
    },
    {
      source: 'gnomad',
      status: 'completed',
      request_identity: { gene: 'RPE65', cdna: 'c.260A>G' },
      summary: {
        allele_count: 2,
        allele_number: 125748,
        allele_frequency: 0.0000159,
        popmax_frequency: 0.0000486,
        popmax_population: 'nfe',
        interpretation: 'Rare in gnomAD v4 joint; no homozygotes reported',
      },
      warnings: [],
      source_url: 'https://gnomad.broadinstitute.org/',
    },
    {
      source: 'alphamissense',
      status: 'completed',
      request_identity: { uniprot_id: 'Q16518', residue: 87 },
      summary: {
        score: 0.71,
        pathogenicity_category: 'likely_pathogenic',
      },
      warnings: [],
      source_url: 'https://alphamissense.hegelab.org/',
    },
  ],
}
