from __future__ import annotations

PUBMED_LOCAL_SCHEMA_VERSION = "eamos.pubmed_local.v4"
PUBMED_LOCAL_SOURCE_ID = "eamos_pubmed_local"
PUBMED_LOCAL_CLI_VERSION = "pubmed-local-cli-v1"
PUBMED_LOCAL_SOURCE_VERSION_PREFIX = "pubmed-local"

PERMISSIVE_LICENSE_PROFILES = {"cc0", "cc_by", "cc_by_sa", "public_domain", "us_government"}
DEFAULT_BIOMEDICAL_DOMAINS = ("gene", "biology", "biochemistry", "chemistry")
DEFAULT_ALLOWED_LANGUAGES = ("eng", "en", "english")
DEFAULT_EXCLUDED_PUBLICATION_TYPES = (
    "autobiography",
    "bibliography",
    "biography",
    "comment",
    "directory",
    "editorial",
    "festschrift",
    "historical article",
    "interview",
    "lecture",
    "legal case",
    "letter",
    "news",
    "newspaper article",
    "patient education handout",
    "popular work",
    "published erratum",
)
NON_BIOMEDICAL_NEGATIVE_MARKERS = (
    "architecture",
    "astronomy",
    "automotive",
    "bridge engineering",
    "civil engineering",
    "climate model",
    "construction",
    "economic",
    "finance",
    "geology",
    "industrial process",
    "mining",
    "optical fiber",
    "petroleum",
    "polymer synthesis",
    "semiconductor",
    "soil mechanics",
    "wastewater",
)
BIOMEDICAL_DOMAIN_MARKERS = {
    "gene": (
        "gene",
        "genes",
        "genetic",
        "genetics",
        "genomic",
        "genomics",
        "variant",
        "variants",
        "mutation",
        "mutations",
        "allele",
        "alleles",
        "hgvs",
        "transcript",
        "chromosome",
        "dna",
        "rna",
    ),
    "biology": (
        "biology",
        "biological",
        "biomedical",
        "biomedical engineering",
        "bioengineering",
        "biomaterial",
        "biomaterials",
        "disease",
        "disorder",
        "phenotype",
        "clinical",
        "patient",
        "patients",
        "cell",
        "cells",
        "tissue",
        "tissue engineering",
        "organism",
        "retinal",
        "ophthalmology",
        "therapy",
    ),
    "biochemistry": (
        "biochemistry",
        "biochemical",
        "protein",
        "proteins",
        "enzyme",
        "enzymatic",
        "metabolic",
        "metabolism",
        "receptor",
        "expression",
        "assay",
        "activity",
        "western blot",
    ),
    "chemistry": (
        "chemical",
        "chemistry",
        "compound",
        "compounds",
        "chemical engineering",
        "molecule",
        "molecules",
        "drug",
        "drugs",
        "ligand",
        "pharmacology",
    ),
}
