import type { LookupResponse } from './backend'

export const RPE65_SAMPLE: LookupResponse = {
  query: 'RPE65 c.260A>G',
  species: 'human',
  warnings: [],
  report_payload: {
    patient_id: 'sample',
    case_label: 'RPE65 p.Asp87Gly',
    report_title: 'RPE65 c.260A>G — Variant Interpretation Report',
    clinical_phenotype: 'Leber Congenital Amaurosis 2 (LCA2) / Retinitis Pigmentosa 20 (RP20). Autosomal recessive retinal dystrophy characterised by severe visual impairment from infancy, nystagmus, and markedly reduced or absent ERG response.',
    ai_clinical_summary:
      'RPE65 p.Asp87Gly is concordant with autosomal recessive retinal dystrophy phenotypes. ClinVar lists it as Likely Pathogenic with two-star review status, supported by REVEL 0.82 — above the strong pathogenic threshold. Three RPE65-related trials are currently recruiting, including Voretigene neparvovec (Luxturna), FDA-approved for biallelic RPE65 retinal dystrophy. Confirmation of homozygosity and segregation testing are the immediate next steps before clinical decision-making proceeds.',
    variant_summary_rows: [
      {
        gene: 'RPE65',
        transcript_hgvs: 'NM_000329.3:c.260A>G',
        protein_change: 'p.Asp87Gly',
        genomic_hg38: 'chr1:68,894,934A>G',
        variation_type: 'SNV',
        consequence: 'missense_variant',
      },
    ],
    acmg_classification: 'Likely Pathogenic — ACMG/AMP criteria: PM1, PM2, PP3 (REVEL 0.82). ClinVar VCV000099473 · 2 stars · 4 submitters.',
    expanded_evidence:
      'ClinVar: Likely Pathogenic (2 stars, 4 submitters, VCV000099473). gnomAD v4: absent from 807,162 alleles (MAF < 1.2e-6). VEP: missense, moderate impact, SIFT deleterious (0.01), PolyPhen-2 probably damaging (0.987). SpliceAI: max delta score 0.04 (below splicing threshold). REVEL: 0.82 — high support for pathogenicity.',
    clinical_integration:
      'Variant is consistent with RPE65-associated Leber Congenital Amaurosis 2 (LCA2) and Retinitis Pigmentosa 20. Biallelic pathogenic variants in RPE65 cause the autosomal recessive form. Luxturna (voretigene neparvovec) is FDA-approved gene therapy for confirmed biallelic RPE65 mutations.',
    expected_symptoms:
      'Severe visual impairment from infancy or early childhood, nystagmus, photophobia, absent or markedly reduced ERG, preserved retinal structure in early years with progressive degeneration.',
    recommendations:
      'Confirm biallelic status: segregation analysis and phasing of any second RPE65 variant. Ophthalmology review with ERG and retinal imaging. Genetic counselling for family members. Evaluate eligibility for Luxturna gene therapy if biallelic RPE65 pathogenic variants confirmed.',
    therapeutic_landscape:
      'Voretigene neparvovec (Luxturna, Spark Therapeutics) is FDA-approved (2017) for confirmed biallelic RPE65 mutation-associated retinal dystrophy. Three additional gene therapy trials are actively recruiting (NCT05858983, NCT04516369, NCT04657926).',
    limitations:
      'Report generated with fixture data in development mode. Evidence reflects database snapshot at time of analysis. ACMG classification requires formal review by a certified variant interpretation laboratory.',
    variant_decoder:
      'c.260A>G — position 260 in the coding sequence of NM_000329.3; adenine substituted by guanine. This changes codon 87 from GAC (Aspartate/Asp/D) to GGC (Glycine/Gly/G). Asp87 is located in the retinoid isomerohydrolase catalytic domain; Gly substitution removes a charged side chain critical for substrate binding.',
    pubmed_articles: [
      {
        pmid: '28274730',
        title: 'Pharmacological and gene therapy based rescue of cytochrome P450-mediated monooxygenase deficiency in RPE65',
        authors: 'Cheng T, Bhatt A, Kulkarni A et al.',
        journal: 'Invest Ophthalmol Vis Sci',
        year: '2017',
        url: 'https://pubmed.ncbi.nlm.nih.gov/28274730/',
      },
    ],
    ai_generated_sections: ['ai_clinical_summary', 'clinical_integration', 'recommendations', 'variant_decoder'],
    locus_context: {
      gene: 'RPE65',
      centre_cdna: 'c.260A>G',
      coords: 'chr1 : 68,444,849 — 68,444,889  ·  RPE65 exon 4  ·  (+) strand',
      nearby_variants: [
        { cds_pos: -42, classification: 'pathogenic',        hgvs: 'c.236A>G', clinvar_id: null,      protein_change: 'p.Asp79Gly' },
        { cds_pos: -32, classification: 'likely_pathogenic', hgvs: 'c.241C>T', clinvar_id: null,      protein_change: 'p.Arg81Cys' },
        { cds_pos: -24, classification: 'pathogenic',        hgvs: 'c.247G>A', clinvar_id: null,      protein_change: 'p.Ala83Thr' },
        { cds_pos: -16, classification: 'vus',               hgvs: 'c.253T>C', clinvar_id: null,      protein_change: null },
        { cds_pos: -8,  classification: 'likely_pathogenic', hgvs: 'c.257C>G', clinvar_id: null,      protein_change: null },
        { cds_pos: 0,   classification: 'likely_pathogenic', hgvs: 'c.260A>G', clinvar_id: '1421454', protein_change: 'p.Asp87Gly' },
        { cds_pos: 8,   classification: 'vus',               hgvs: 'c.268A>G', clinvar_id: null,      protein_change: null },
        { cds_pos: 16,  classification: 'likely_benign',     hgvs: 'c.271G>A', clinvar_id: null,      protein_change: null },
        { cds_pos: 24,  classification: 'pathogenic',        hgvs: 'c.277C>T', clinvar_id: null,      protein_change: 'p.Arg93Cys' },
        { cds_pos: 32,  classification: 'vus',               hgvs: 'c.283G>C', clinvar_id: null,      protein_change: null },
        { cds_pos: 40,  classification: 'likely_pathogenic', hgvs: 'c.289G>A', clinvar_id: null,      protein_change: 'p.Glu97Lys' },
      ],
      codon_strip: [
        { codon_number: 82, aa_ref: 'Y', aa_alt: null, dna_ref: 'TAT', dna_alt: null,  is_query: false },
        { codon_number: 83, aa_ref: 'R', aa_alt: null, dna_ref: 'CGG', dna_alt: null,  is_query: false },
        { codon_number: 84, aa_ref: 'E', aa_alt: null, dna_ref: 'GAA', dna_alt: null,  is_query: false },
        { codon_number: 85, aa_ref: 'P', aa_alt: null, dna_ref: 'CCT', dna_alt: null,  is_query: false },
        { codon_number: 86, aa_ref: 'V', aa_alt: null, dna_ref: 'GTG', dna_alt: null,  is_query: false },
        { codon_number: 87, aa_ref: 'D', aa_alt: 'G',  dna_ref: 'GAC', dna_alt: 'GGC', is_query: true },
        { codon_number: 88, aa_ref: 'K', aa_alt: null, dna_ref: 'AAG', dna_alt: null,  is_query: false },
        { codon_number: 89, aa_ref: 'T', aa_alt: null, dna_ref: 'ACA', dna_alt: null,  is_query: false },
        { codon_number: 90, aa_ref: 'V', aa_alt: null, dna_ref: 'GTC', dna_alt: null,  is_query: false },
        { codon_number: 91, aa_ref: 'A', aa_alt: null, dna_ref: 'GCC', dna_alt: null,  is_query: false },
        { codon_number: 92, aa_ref: 'I', aa_alt: null, dna_ref: 'ATT', dna_alt: null,  is_query: false },
      ],
    },
    in_silico_predictions: {
      cards: [
        { name: 'REVEL',         score: 0.82, threshold: 0.75, verdict: 'damaging',  verdict_label: 'Pathogenic supporting', source_url: 'https://sites.google.com/site/revelgenomics' },
        { name: 'AlphaMissense', score: 0.91, threshold: 0.56, verdict: 'damaging',  verdict_label: 'Likely pathogenic',     source_url: 'https://alphamissense.hegelab.org' },
        { name: 'MetaLR',        score: 0.78, threshold: 0.50, verdict: 'damaging',  verdict_label: 'Deleterious',           source_url: null },
        { name: 'SpliceAI',      score: 0.05, threshold: 0.20, verdict: 'tolerated', verdict_label: 'No splice impact',      source_url: 'https://spliceailookup.broadinstitute.org' },
      ],
      consensus_note:
        'Predictors converge: the protein-effect predictors all cross their pathogenic thresholds, while SpliceAI sits well below the 0.20 splice-altering cutoff. No disagreement to flag — the in-silico signal is internally consistent with the ClinVar Likely Pathogenic call.',
    },
    acmg_criteria_scaffold: {
      criteria: [
        { code: 'PVS1', verdict: 'not_met' },
        { code: 'PS1',  verdict: 'not_met' },
        { code: 'PS2',  verdict: 'not_assessed' },
        { code: 'PS3',  verdict: 'not_assessed' },
        { code: 'PS4',  verdict: 'not_assessed' },
        { code: 'PM1',  verdict: 'not_met' },
        { code: 'PM2',  verdict: 'met', note: 'Absent from gnomAD v4 (>250k alleles).' },
        { code: 'PM3',  verdict: 'not_assessed' },
        { code: 'PM4',  verdict: 'not_met' },
        { code: 'PM5',  verdict: 'met', note: 'Different missense at same codon previously classified pathogenic.' },
        { code: 'PM6',  verdict: 'not_assessed' },
        { code: 'PP1',  verdict: 'not_assessed' },
        { code: 'PP2',  verdict: 'not_met' },
        { code: 'PP3',  verdict: 'met', note: 'Multiple in-silico predictors agree on damaging.' },
        { code: 'PP4',  verdict: 'met', note: 'Phenotype highly specific for RPE65-related disease.' },
        { code: 'PP5',  verdict: 'not_assessed' },
        { code: 'BA1',  verdict: 'not_met' },
        { code: 'BS1',  verdict: 'not_met' },
        { code: 'BS2',  verdict: 'not_assessed' },
        { code: 'BS3',  verdict: 'not_assessed' },
        { code: 'BS4',  verdict: 'not_assessed' },
        { code: 'BP1',  verdict: 'not_met' },
        { code: 'BP2',  verdict: 'not_assessed' },
        { code: 'BP3',  verdict: 'not_met' },
        { code: 'BP4',  verdict: 'not_met' },
        { code: 'BP5',  verdict: 'not_assessed' },
        { code: 'BP6',  verdict: 'not_assessed' },
        { code: 'BP7',  verdict: 'not_met' },
      ],
      intro:
        'An automated read of the standard ACMG/AMP criteria for this variant. This is supporting evidence, not a classification. Eamos does not issue ACMG classifications — clinical judgement, segregation, and functional data are required before a final call.',
      note:
        'Met criteria above provide moderate-to-supporting evidence consistent with the Likely Pathogenic ClinVar classification. The unmet criteria reflect evidence types that haven’t been observed for this variant (e.g. functional studies, de novo observation) — they do not contradict pathogenicity.',
      disclaimer: 'Supporting evidence, not classification.',
    },
    curated_variants_distribution: {
      cells: {
        pathogenic_lof: 210,
        pathogenic_missense: 187,
        pathogenic_noncoding: 6,
        pathogenic_synonymous: 3,
        vus_lof: 1,
        vus_missense: 342,
        vus_noncoding: 51,
        vus_synonymous: 32,
        benign_lof: 0,
        benign_missense: 11,
        benign_noncoding: 198,
        benign_synonymous: 245,
      },
      row_totals: { pathogenic: 406, vus: 426, benign: 454 },
      total: 1286,
      subtitle: '1,286 classified variants · ClinVar + UniProt',
      reading:
        'LOF and missense both contribute substantially to pathogenicity in RPE65 — LOF is a well-established disease mechanism. The 342 missense VUS reflect the deep interpretation tail typical of recessive disease genes.',
    },
    associated_conditions: [
      { name: 'Leber Congenital Amaurosis 2 (LCA2)',                 case_count: 412, evidence_level: 'definitive', inheritance: 'AR', source: 'OMIM #204100',            db_tag: '#204100',               db_tag_bold: 'OMIM', source_list: 'OMIM · Monarch · DECIPHER · GenCC · ClinGen' },
      { name: 'Retinitis Pigmentosa 20 (RP20)',                      case_count: 218, evidence_level: 'definitive', inheritance: 'AR', source: 'OMIM #613794',            db_tag: '#613794',               db_tag_bold: 'OMIM', source_list: 'OMIM · Monarch · GenCC' },
      { name: 'RPE65-Related Dominant Retinopathy',                  case_count: 14,  evidence_level: 'moderate',   inheritance: 'AD', source: 'No OMIM entry',           db_tag: 'No OMIM entry',         db_tag_bold: null,   source_list: 'OMIM · GenCC · ClinGen · MONDO' },
      { name: 'Severe Early-Childhood-Onset Retinal Dystrophy',      case_count: 9,   evidence_level: 'moderate',   inheritance: 'AR', source: 'Orphanet ORPHA:71862',    db_tag: 'Orphanet ORPHA:71862',  db_tag_bold: null,   source_list: 'Orphanet · GenCC' },
      { name: 'RPE65-Related Recessive Retinopathy (umbrella)',      case_count: 5,   evidence_level: 'definitive', inheritance: 'AR', source: 'MONDO:0019200',           db_tag: 'MONDO:0019200',         db_tag_bold: null,   source_list: 'PubMed · GenCC · MONDO · DECIPHER · OMIM · ClinGen' },
    ],
    publications_callout: {
      total_count: 816,
      scholar_url: 'https://scholar.google.com/scholar?q=RPE65+Asp87Gly',
      blurb: 'Across PubMed and Google Scholar for RPE65 + p.Asp87Gly. Ask Eamos for a synthesis of the top 5, or browse externally.',
      ai_summary_prompt: 'Summarise the key publications on RPE65 c.260A>G in plain language for a clinician.',
    },
  },
  evidence: [
    {
      source: 'clinvar',
      status: 'completed',
      request_identity: { gene: 'RPE65', cdna: 'c.260A>G' },
      summary: {
        classification: 'Likely pathogenic',
        review_stars: 2,
        submitter_count: 4,
        accession: 'VCV000099473',
        condition: 'Leber congenital amaurosis 2',
      },
      warnings: [],
      source_url: 'https://www.ncbi.nlm.nih.gov/clinvar/variation/99473/',
    },
    {
      source: 'vep',
      status: 'completed',
      request_identity: { transcript: 'NM_000329.3', cdna: 'c.260A>G' },
      summary: {
        consequence: 'missense_variant',
        impact: 'MODERATE',
        sift: { pred: 'deleterious', score: 0.01 },
        polyphen: { pred: 'probably_damaging', score: 0.987 },
        revel: 0.82,
      },
      warnings: [],
      source_url: 'https://www.ensembl.org/Tools/VEP',
    },
    {
      source: 'spliceai',
      status: 'completed',
      request_identity: { gene: 'RPE65', cdna: 'c.260A>G' },
      summary: {
        max_delta: 0.04,
        interpretation: 'Low splicing impact',
      },
      warnings: [],
      source_url: 'https://spliceailookup.broadinstitute.org/',
    },
    {
      source: 'gnomad',
      status: 'completed',
      request_identity: { gene: 'RPE65', cdna: 'c.260A>G' },
      summary: {
        allele_count: 0,
        allele_number: 807162,
        allele_frequency: null,
        interpretation: 'Absent from gnomAD v4',
      },
      warnings: [],
      source_url: 'https://gnomad.broadinstitute.org/',
    },
    {
      source: 'alphamissense',
      status: 'completed',
      request_identity: { uniprot_id: 'Q16518', residue: 87 },
      summary: {
        score: 0.71,
        pathogenicity_category: 'likely_pathogenic',
      },
      warnings: [],
      source_url: 'https://alphamissense.hegelab.org/',
    },
  ],
}
